[7:04 PM, 7/12/2021] Yuvaraj Ltts: name:  Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install gcov
      run: sudo apt -y install gcovr 
    - name: code coverage
      run: make -C 03_Implementation/ coverage
[7:05 PM, 7/12/2021] Yuvaraj Ltts: name: Dynamic code analysis
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install dependency
      run: |
        sudo apt-get -y install valgrind
        sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 
    - name: make test
      run: make -C 3_Implementation/ test
    - name: Valgrind
      run: make -C 3_Implementation/ valgrind
